version: '3'
services:
  leaguebot:
    container_name: leaguebot
    image: node:latest
    volumes:
        - .:/usr/src/leaguebot
        - leaguebot_node_modules:/usr/src/leaguebot/node_modules
    working_dir: /usr/src/leaguebot
    command: npm run dev
    environment:
        - NODE_ENV=development
    ports:
        - 9229:9229

volumes:
    leaguebot_node_modules:
        external: true
